### PR TITLE
ci: Test crossdev in GitHub Actions

### PR DESCRIPTION
**Pull request by vadorovsky**
Add a workflow which sets up and tests crossdev for the given list of targets.

### CODE REVIEW

**Comment by thesamesam** [comment]
Could you add Signed-off-by?

**Comment by vadorovsky** [comment]
Done

**Comment by thesamesam** [comment]
Looks like it ran but failed - please take a look. Thanks!

**Comment by vadorovsky** [comment]
Yes, I will create a PR attempting to fix it.

**Pull request closed without merging**
